services:
  teledav:
    build: .
    container_name: teledav
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${DAV_PORT}"
    volumes:
      - ./teledav.db:/app/teledav.db